# Streamwall Suite - One-Click Setup
# Just run: docker compose up

services:
  # Database
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: streamwall
      POSTGRES_USER: streamwall
      POSTGRES_PASSWORD: streamwall
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U streamwall"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Cache
  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Main API
  streamsource:
    build: ./streamsource
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://streamwall:streamwall@postgres:5432/streamwall
      REDIS_URL: redis://redis:6379/0
      SECRET_KEY_BASE: development_secret_key_must_be_at_least_30_chars
      JWT_SECRET: development_jwt_secret_also_30_chars_minimum
      RAILS_LOG_TO_STDOUT: "true"
    volumes:
      - ./streamsource:/rails
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: ["./bin/rails", "server", "-b", "0.0.0.0"]

  # Stream Monitor (Optional - needs Discord/Twitch tokens)
  monitor:
    build: ./livestream-link-monitor
    environment:
      STREAMSOURCE_API_URL: http://streamsource:3000/api/v1
      STREAMSOURCE_API_KEY: dev_monitor_key
      # Add these to .env file:
      DISCORD_TOKEN: ${DISCORD_TOKEN:-}
      DISCORD_GUILD_ID: ${DISCORD_GUILD_ID:-}
      DISCORD_CHANNEL_IDS: ${DISCORD_CHANNEL_IDS:-}
      TWITCH_CLIENT_ID: ${TWITCH_CLIENT_ID:-}
      TWITCH_CLIENT_SECRET: ${TWITCH_CLIENT_SECRET:-}
      TWITCH_CHANNELS: ${TWITCH_CHANNELS:-}
    volumes:
      - ./livestream-link-monitor:/app
    depends_on:
      - streamsource

  # Status Updater
  updater:
    build: ./livesheet-updater
    environment:
      STREAMSOURCE_API_URL: http://streamsource:3000/api/v1
      STREAMSOURCE_API_KEY: dev_updater_key
      CHECK_INTERVAL_SECONDS: 60
    volumes:
      - ./livesheet-updater:/app
    depends_on:
      - streamsource

volumes:
  postgres_data:

networks:
  default:
    name: streamwall